#!/bin/bash

set -e

cd "${0%/*}"

xcodebuild clean -configuration Debug -sdk iphoneos
xcodebuild clean -configuration Debug -sdk iphonesimulator
xcodebuild clean -configuration Release -sdk iphoneos
xcodebuild clean -configuration Release -sdk iphonesimulator

xcodebuild -target EmarsysPredictSDK -configuration Debug -sdk iphoneos ONLY_ACTIVE_ARCH=NO
xcodebuild -target EmarsysPredictSDK -configuration Debug -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
xcodebuild -target EmarsysPredictSDK -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO
xcodebuild -target EmarsysPredictSDK -configuration Release -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
