#!/bin/bash

set -e

cd "${0%/*}"

headerdoc2html -o ./doc ./EmarsysPredictSDK/EMCartItem.h ./EmarsysPredictSDK/EMError.h ./EmarsysPredictSDK/EMRecommendationItem.h ./EmarsysPredictSDK/EMRecommendationRequest.h ./EmarsysPredictSDK/EMRecommendationResult.h ./EmarsysPredictSDK/EMSession.h ./EmarsysPredictSDK/EMTransaction.h

gatherheaderdoc .